# For PRs, build the docker container, run tests, coverage and build doc and wheel.
name: Docker Unit Tests
on: [ push, workflow_dispatch ]


env:
  # Make sure these secrets are set in this git repo or organisation settings:

  # Private package index credentials, for installing and publishing to
  PUBLISH_URL: ${{secrets.PUBLISH_URL}}
  PUBLISH_USER: ${{secrets.PUBLISH_USER}}
  PUBLISH_PASSWORD: ${{secrets.PUBLISH_PASSWORD}}

  # URL with UN and PW for postgres database
  DB_URL: ${{ secrets.DB_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dock-compose build
        run: docker-compose build

      - name: Run tests in docker
        run: docker-compose run test




