# For PRs, build the docker container, run tests, coverage etc.
name: Docker Unit Tests
on: [ push, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dock-compose build
        run: docker-compose build

      - name: Run tests in docker
        run: docker-compose run test




